
const AUDIT_ACTIONS = {
    TASK_CREATED: 'TASK_CREATED',
    TASK_UPDATED: 'TASK_UPDATED',
    TASK_DELETED: 'TASK_DELETED',
    TASK_VIEWED: 'TASK_VIEWED',
    TASK_LISTED: 'TASK_LISTED',
    USER_REGISTERED: 'USER_REGISTERED',
    USER_LOGGED_IN: 'USER_LOGGED_IN',
  };
  
  module.exports = AUDIT_ACTIONS;
  